name: Sauce Demo Automated Test Run

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npm run cypress:run

      - name: Generate Mochawesome Report
        run: npm run report:generate

      - name: Upload Mochawesome HTML report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/results/
          include-hidden-files: true